In [1]:
import pandas as pd

# Membaca file CSV (pastikan nama file di bawah ini sama persis dengan nama file CSV)
df = pd.read_csv('indonesia_ecommerce_apparel_2023_2025.csv')

# Menampilkan 5 baris pertama dari dataset untuk mengecek apakah data sudah masuk
df.head()

,Order_ID,Transaction_Date,Product_Category,Unit_Price,Quantity,Discount_Amount,Shipping_City,Payment_Method,Shipping_Cost,Order_Status
0,ORD-2023-00001,2023-01-01 01:15:51,Tank Top,99000,3,80000.0,Kediri,E-Wallet,21500,Completed
1,ORD-2023-00002,2023-01-01 02:29:41,Celana Chino,223000,1,53000.0,Batam,Kartu Kredit,23500,Completed
2,ORD-2023-00003,2023-01-01 03:54:18,Kaos Grafis,195000,1,21000.0,Tangerang Selatan,COD,14000,Completed
3,ORD-2023-00004,2023-01-01 05:05:28,Celana Chino,345000,4,191000.0,Surabaya,COD,13500,Completed
4,ORD-2023-00005,2023-01-01 05:19:16,Rok Mini,184000,1,46000.0,Jakarta Timur,Transfer Bank,13000,Completed

# FASE 2.1 Data Cleaning & Eksplorasi.

Langkah 1: Memeriksa "Kesehatan" Data Secara Umum ||
Kita perlu tahu seberapa besar datamu, tipe datanya apa saja, dan apakah ada nilai yang bolong (kosong/NaN).

In [2]:
# 1. Melihat rangkuman dataset (jumlah baris, kolom, dan tipe data)
print("=== INFO DATASET ===")
df.info()

print("\n=== JUMLAH DATA KOSONG (NaN) ===")
# 2. Menghitung jumlah data yang bolong di setiap atribut
print(df.isnull().sum())

=== INFO DATASET ===
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          50000 non-null  str
 1   Transaction_Date  50000 non-null  str
 2   Product_Category  50000 non-null  str
 3   Unit_Price        50000 non-null  int64
 4   Quantity          50000 non-null  int64
 5   Discount_Amount   49500 non-null  float64
 6   Shipping_City     50000 non-null  str
 7   Payment_Method    49500 non-null  str
 8   Shipping_Cost     50000 non-null  int64
 9   Order_Status      50000 non-null  str
dtypes: float64(1), int64(3), str(6)
memory usage: 3.8 MB

=== JUMLAH DATA KOSONG (NaN) ===
Order_ID              0
Transaction_Date      0
Product_Category      0
Unit_Price            0
Quantity              0
Discount_Amount     500
Shipping_City         0
Payment_Method      500
Shipping_Cost         0
Order_Status          0
dtype: int64

Langkah 2: Memperbaiki Tipe Data Waktu ||
Biasanya, saat kita load CSV, kolom tanggal (Transaction_Date) masih terbaca sebagai teks biasa (string/object). Kita harus mengubahnya menjadi format kalender resmi di Pandas agar nanti bisa ditarik metrik "penjualan per bulan".

In [3]:
# Mengubah kolom Transaction_Date menjadi format tipe data datetime
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])

# Cek kembali apakah tipenya sudah berubah menjadi datetime64
print("Tipe data Transaction_Date sekarang:", df['Transaction_Date'].dtype)

Tipe data Transaction_Date sekarang: datetime64[us]

Langkah 3: Mengecek Typo dan Data Aneh (Eksplorasi) ||
Cek ada typo apa saja di nama kota atau kategori produk.

In [4]:
# Cek nilai unik di kolom kategori untuk melihat apakah ada nama yang aneh
print("=== KATEGORI PRODUK ===")
print(df['Product_Category'].unique())

print("\n=== DAFTAR KOTA PENGIRIMAN ===")
print(df['Shipping_City'].unique())

print("\n=== METODE PEMBAYARAN ===")
print(df['Payment_Method'].unique())

=== KATEGORI PRODUK ===
<StringArray>
[         'Tank Top',      'Celana Chino',       'Kaos Grafis',
          'Rok Mini',        'Kaos Polos',       'Jaket Denim',
     'Kemeja Casual',      'Celana Jeans',          'Cardigan',
           'Sweater',      'Jaket Hoodie',            'Blouse',
      'Dress Casual',     'Celana Pendek', 'Jaket Windbreaker',
             'Outer',     'Kemeja Formal',      'Dress Formal',
        'Polo Shirt',          'Rok Midi']
Length: 20, dtype: str

=== DAFTAR KOTA PENGIRIMAN ===
<StringArray>
[            'Kediri',              'Batam',  'Tangerang Selatan',
           'Surabaya',      'Jakarta Timur',           'Jayapura',
      'Jakarta Utara',         'Yogyakarta',          'Pontianak',
              'Medan',      'Jakarta Pusat',           'Semarang',
      'Jakarta Barat',              'Bogor',          'Tangerang',
             'Bekasi',         'Purwokerto',          'Palembang',
             'Manado',             'Malang',           'Denpasar',
     'Bandar Lampung',            'Bandung',         'Balikpapan',
            'Cirebon',              'Ambon',          'Sukabumi ',
          'Pekanbaru',               'Solo',             'Jember',
            'Mataram',    'Jakarta Selatan',           'Makassar',
          'Surabaya ',        'Banjarmasin',              'Depok',
          'Samarinda',             'Kupang',           'Sukabumi',
        'Tasikmalaya',            'Padang ',           'Semerang',
             'Padang',      'Jakarta Utraa',         'Tangerang ',
             'Sorong',    'Jakrata Selatan',       'JakartaUtara',
             'Ambon ',            'Bekasi ',            'Malang ',
             'Bandun',         'Samarinda ',   'Jakarta Selatan ',
       'Tasikmalaya ',             'Bogor ',            'Jember ',
            'Kupang ',            'Manado ',     'Jakarta Barat ',
         'Jogyakarta',     'Jakarta Pusat ',              'Solo ',
         'Pekanbaru ',          'Denpasaar',     'Jakarta Timur ',
 'Tangerang Selatan ',         'Palembang ',           'Cirebon ',
             'Badung',        'Purwokerto ',         'Yogjakarta',
             'Batam ',            'Makasar',           'Mataram ',
             'Medan ',            'Sorong ',        'Balikapapan',
             'Depok ',          'Denpasar ',           'Makasaar',
       'Banjarmasin ',            'Surabay',            'Semrang',
             'Medaan',            'Kediri ',    'Bandar Lampung ',
         'Pontianak ',          'Jayapura ',          'Balikppan']
Length: 90, dtype: str

=== METODE PEMBAYARAN ===
<StringArray>
['E-Wallet', 'Kartu Kredit', 'COD', 'Transfer Bank', nan]
Length: 5, dtype: str

Langkah 4: Cek Logika Angka ||
 Cek kolom yang berisi angka (harga, kuantitas). Tidak boleh ada harga barang yang minus atau diskon yang lebih besar dari harga barangnya.

In [5]:
# Menampilkan statistik dasar (nilai minimum, maksimum, rata-rata)
# Perhatikan baris 'min', apakah ada angka minus di Unit_Price atau Quantity?
df.describe()

,Transaction_Date,Unit_Price,Quantity,Discount_Amount,Shipping_Cost
count,50000,50000.000000,50000.000000,49500.000000,50000.00000
mean,2024-06-29 23:42:28.789440,212080.540000,2.093740,41102.181818,18571.13970
min,2023-01-01 01:15:51,-491000.000000,-1.000000,0.000000,0.00000
25%,2023-09-29 13:29:32.750000,141000.000000,1.000000,0.000000,11500.00000
50%,2024-06-28 16:52:06.500000,201000.000000,2.000000,21000.000000,14500.00000
75%,2025-03-28 21:31:37.750000,278000.000000,3.000000,57000.000000,21000.00000
max,2025-12-31 23:33:21,499000.000000,5.000000,714000.000000,493531.00000
std,NaN,103481.257727,1.182413,60240.529678,18758.39383

# FASE 2.2 :  DATA CLEANING

In [6]:
from thefuzz import process

# 1. Memangkas spasi berlebih (depan/belakang) pada kolom teks
df['Shipping_City'] = df['Shipping_City'].str.strip()

# --- MENGGUNAKAN FUZZY MATCHING SEBAGAI PENGGANTI KAMUS ---
# Daftar Master Kota yang Benar (Bisa ditambah jika dirasa kurang)
kota_master = [
    'Ambon', 'Badung', 'Balikpapan', 'Bandar Lampung', 'Bandung', 'Banjarmasin', 
    'Batam', 'Bekasi', 'Bogor', 'Cirebon', 'Denpasar', 'Depok', 'Jakarta Barat', 
    'Jakarta Pusat', 'Jakarta Selatan', 'Jakarta Timur', 'Jakarta Utara', 
    'Jayapura', 'Jember', 'Kediri', 'Makassar', 'Malang', 'Manado', 'Mataram', 
    'Medan', 'Palembang', 'Pekanbaru', 'Pontianak', 'Purwokerto', 'Semarang', 
    'Solo', 'Sukabumi', 'Surabaya', 'Tangerang', 'Tangerang Selatan', 'Yogyakarta'
]

# Fungsi otomatis untuk mencari kemiripan
def fix_city_fuzzy(city_name):
    best_match, score = process.extractOne(city_name, kota_master)
    if score >= 80: # Jika mirip 80% atau lebih, ubah ke nama master
        return best_match
    else:
        return city_name

# Menerapkan fungsi fuzzy ke kolom kota
df['Shipping_City'] = df['Shipping_City'].apply(fix_city_fuzzy)

# Cek kembali daftar kota untuk memastikan sudah rapi
print("=== DAFTAR KOTA SETELAH FUZZY MATCHING ===")
print(sorted(df['Shipping_City'].unique()))

# ---------------------------------------------------------------

# 2. Menangani nilai kosong (NaN)
# Jika diskon kosong, asumsikan tidak ada diskon (diisi angka 0)
df['Discount_Amount'] = df['Discount_Amount'].fillna(0)
# Jika metode pembayaran kosong, kategorikan sebagai 'Lainnya'
df['Payment_Method'] = df['Payment_Method'].fillna('Lainnya')

# 3. Menangani angka minus (Typo sistem)
# Diasumsikan tanda minus adalah kesalahan ketik, jadi ubah jadi positif (absolut)
df['Unit_Price'] = df['Unit_Price'].abs()
df['Quantity'] = df['Quantity'].abs()

=== DAFTAR KOTA SETELAH FUZZY MATCHING ===
['Ambon', 'Badung', 'Balikpapan', 'Bandar Lampung', 'Bandung', 'Banjarmasin', 'Batam', 'Bekasi', 'Bogor', 'Cirebon', 'Denpasar', 'Depok', 'Jakarta Barat', 'Jakarta Pusat', 'Jakarta Selatan', 'Jakarta Timur', 'Jakarta Utara', 'Jayapura', 'Jember', 'Kediri', 'Kupang', 'Makassar', 'Malang', 'Manado', 'Mataram', 'Medan', 'Padang', 'Palembang', 'Pekanbaru', 'Pontianak', 'Purwokerto', 'Samarinda', 'Semarang', 'Solo', 'Sorong', 'Sukabumi', 'Surabaya', 'Tangerang', 'Tangerang Selatan', 'Tasikmalaya', 'Yogyakarta']

# FASE 3: FEATURE ENGINEERING & EXPORT (MEMBUAT METRIK)

In [7]:
# 1. Membuat kolom Total Penjualan Bersih per transaksi
df['Net_Sales'] = (df['Unit_Price'] * df['Quantity']) - df['Discount_Amount']

# 2. Mengekstrak waktu agar mudah divisualisasikan di Power BI
df['Nama_Bulan'] = df['Transaction_Date'].dt.month_name()
df['Nama_Hari'] = df['Transaction_Date'].dt.day_name()
df['Jam_Transaksi'] = df['Transaction_Date'].dt.hour

# 3. Menyimpan hasil akhir menjadi file CSV baru yang bersih
df.to_csv('ecommerce_cleaned_ready.csv', index=False)

print("Pembersihan selesai! Data siap divisualisasikan.")
print("\nContoh 3 baris data terbaru:")
print(df[['Transaction_Date', 'Unit_Price', 'Quantity', 'Net_Sales', 'Nama_Bulan']].head(3))

Pembersihan selesai! Data siap divisualisasikan.

Contoh 3 baris data terbaru:
     Transaction_Date  Unit_Price  Quantity  Net_Sales Nama_Bulan
0 2023-01-01 01:15:51       99000         3   217000.0    January
1 2023-01-01 02:29:41      223000         1   170000.0    January
2 2023-01-01 03:54:18      195000         1   174000.0    January